# 服务端口与统一API前缀
server:
  port: 8080
  servlet:
    context-path: /api

# 数据库、JPA配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: JDBC:mysql://localhost:3306/library_management
    username: root # 替换成你本地MySQL账号
    password: 123456 # 替换成你本地MySQL密码
  mail:
    host: smtp.qq.com
    port: 587
    username: 2051095129@qq.com  # 你的完整QQ邮箱
    password: plhzmhpnhsgdbhbi  # 这里粘贴刚拿到的16位授权码，不是QQ密码
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  devtools:
    restart:
      enabled: false # 你不需要热部署，直接关闭

# JWT自定义参数
jwt:
  secret: library-spring-2026-jwt-secret-key-aaa123456
  expiration: 86400000